/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import utils.CardSwitcher;
import utils.ImageUtil;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.util.Random;
import javax.swing.AbstractAction;
import javax.swing.KeyStroke;
import javax.swing.Timer;
import gameCode.PredatorPreyModels;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import gameCode.SimulationUpdateData;

/**
 *
 * @author michael.roy-diclemente
 */
public class GamePanel extends javax.swing.JPanel implements MouseListener {
    //initialize random
    Random r = new Random();
    
    public static final String CARD_NAME = "game";

    CardSwitcher switcher; // This is the parent panel
    
    //Timer
    Timer animTimer;
    
    //Images
    BufferedImage preyImg;
    BufferedImage predImg;
    BufferedImage obstacleImg;
    BufferedImage backgroundImg;
    
    //constants
    final int gridSize = 20;
    
    //position strings
    String prey = "";
    String predator = "";
    String obstacle = "";
    
    //pred info strings
    String predAte = "";
    String predMoved = "";
    
    //create the grid
    String[][] grid = new String[gridSize][gridSize];
    
    //game variables
    boolean startGame = false;
    int preyRepRate = 12;
    int count = 0;
    int speed = 50;
    
    
    /**
     * Creates new form GamePanel
     */
    public GamePanel(CardSwitcher p) {
        initComponents();
        
        //initialize the image
        preyImg = ImageUtil.loadAndResizeImage("chocolate.png", 16, 16);
        predImg = ImageUtil.loadAndResizeImage("Bob.png", 16, 16);
        obstacleImg = ImageUtil.loadAndResizeImage("gradingHomework.png", 16, 16);
        backgroundImg = ImageUtil.loadAndResizeImage("floor.jpg", 256, 144);
        
        this.setFocusable(true);

        // tell the program we want to listen to the mouse
        addMouseListener(this);
        
        //tells us the panel that controls this one
        switcher = p;
        
        //create and start a Timer for animation
        animTimer = new Timer(10, new AnimTimerTick());
        animTimer.start();

        //set up the key bindings
        setupKeys();
        
        //setup the grid
        for (int i = 0; i < gridSize; i++) {
            for (int j = 0; j < gridSize; j++) {
                grid[i][j] = ".";
            }
        }
    }

    private void setupKeys() {
        //these lines map a physical key, to a name, and then a name to an 'action'.  You will change the key, name and action to suit your needs
        this.getInputMap().put(KeyStroke.getKeyStroke("LEFT"), "leftKey");
        this.getActionMap().put("leftKey", new Move("LEFT"));

        this.getInputMap().put(KeyStroke.getKeyStroke("W"), "wKey");
        this.getActionMap().put("wKey", new Move("w"));

        this.getInputMap().put(KeyStroke.getKeyStroke("D"), "dKey");
        this.getActionMap().put("dKey", new Move("d"));

        this.getInputMap().put(KeyStroke.getKeyStroke("X"), "xKey");
        this.getActionMap().put("xKey", new Move("x"));
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        //draw background image
        for (int i = 0; i < 3; i++) {
            g.drawImage(backgroundImg, 0, 144 * i, this);
            g.drawImage(backgroundImg, 256, 144 * i, this);
        }
        
        //draw grid
        g.setColor(Color.WHITE);
        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(2));
        
        for (int i = 0; i < 21; i++) {
            g.drawLine(i * 16 + 40, 20, i * 16 + 40, 340);
        }
        for (int i = 0; i < 21; i++) {
            g.drawLine(40, i * 16 + 20, 360, i * 16 + 20);
        } 
        
        //draw prey, pred, and obstacles on the panel
        for (int i = 0; i < (predator.length() + 1)/3; i++) {
            g.drawImage(predImg, (predator.charAt(i * 3) - 65) * 16 + 40, (predator.charAt(i * 3 + 1) - 65) * 16 + 20, this);
        }
        for (int i = 0; i < (prey.length() + 1)/3; i++) {
            g.drawImage(preyImg, (prey.charAt(i * 3) - 65) * 16 + 40, (prey.charAt(i * 3 + 1) - 65) * 16 + 20, this);
        }
        for (int i = 0; i < (obstacle.length())/3; i++) {
            g.drawImage(obstacleImg, (obstacle.charAt(i * 3) - 65) * 16 + 40, (obstacle.charAt(i * 3 + 1) - 65) * 16 + 20, this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResetButton = new javax.swing.JButton();
        StartButton = new javax.swing.JButton();

        ResetButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        ResetButton.setText("RESET");
        ResetButton.setPreferredSize(new java.awt.Dimension(104, 40));
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        StartButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        StartButton.setText("START");
        StartButton.setPreferredSize(new java.awt.Dimension(104, 40));
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        startGame = false;
        
        //reset the variables
        prey = "";
        predator = "";
        obstacle = "";
        grid = new String[gridSize][gridSize];
        
        //reenable the start button
        StartButton.setEnabled(true);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        //start the game
        startGame = true;
        
        //adjust the string size
        prey = prey.substring(0, prey.length() - 1);
        predator = predator.substring(0, predator.length() - 1);
        
        //create the pred info strings
        for (int i = 0; i < (predator.length() + 1)/3; i++) {
            predAte += "T ";
        }
        
        for (int i = 0; i < (predator.length() + 1)/3; i++) {
            predMoved += "F ";
        }
        
        //disable button to prevent the user from breaking the game
        StartButton.setEnabled(false);
    }//GEN-LAST:event_StartButtonActionPerformed
    
    //mouse events
    public void mouseClicked(MouseEvent me) {
        if (me.getX() > 40 && me.getX() < 360 && me.getY() > 20 && me.getY() < 340) {
            if (me.getButton() == MouseEvent.BUTTON1) { //left click to place prey
                prey += ((char) ((me.getX() - 40)/16 + 65) + "" + (char) ((me.getY() - 20)/16 + 65) + " ");
                grid[(me.getX() - 40)/16][(me.getY() - 20)/16] = "@";
            }
            else if (me.getButton() == MouseEvent.BUTTON2) { //middle click to place obstacles
                obstacle += ((char) ((me.getX() - 40)/16 + 65) + "" + (char) ((me.getY() - 20)/16 + 65) + " ");
                grid[(me.getX() - 40)/16][(me.getY() - 20)/16] = "*";
            }
            else if (me.getButton() == MouseEvent.BUTTON3) { //right click to place pred
                predator += ((char) ((me.getX() - 40)/16 + 65) + "" + (char) ((me.getY() - 20)/16 + 65) + " ");
                grid[(me.getX() - 40)/16][(me.getY() - 20)/16] = "P";
            }
        }
    }
    public void mousePressed(MouseEvent me) {
    }
    public void mouseReleased(MouseEvent me) {
    }
    public void mouseEntered(MouseEvent me) {
    }
    public void mouseExited(MouseEvent me) {
        System.out.println("Exit: " + me.getX() + ":" + me.getY());
    }

    /**
     * Everything inside here happens when you click on a captured key.
     */
    private class Move extends AbstractAction {
        String key;

        public Move(String akey) {
            key = akey;
        }

        public void actionPerformed(ActionEvent ae) {
        }
    }

    /**
     * Everything inside this actionPerformed will happen every time the
     * animation timer clicks.
     */
    private class AnimTimerTick implements ActionListener {
        public void actionPerformed(ActionEvent ae) {
            if (startGame) {
                count += 1;
                if (count % speed == 0) {
                    SimulationUpdateData data = PredatorPreyModels.simulateProgramOnce(prey, predator, obstacle, predAte, predMoved, preyRepRate, grid, 20);
                    
                    prey = data.getPrey();
                    predator = data.getPredator();
                    predAte = data.getPredAte();
                    predMoved = data.getPredMoved();
                    preyRepRate = data.getPreyRepRate();
                    grid = data.getGrid();
                }
            }
            
            //force redraw
            repaint();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton StartButton;
    // End of variables declaration//GEN-END:variables
}
