/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import utils.CardSwitcher;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import javax.swing.Timer;
import utils.ImageUtil;

/**
 * Panel displaying the intro screen for the game.
 * Allows the user to either play the game or read the instructions about how to play from this screen.
 * @author Ethan Li
 */
public class IntroPanel extends javax.swing.JPanel {
    public static final String CARD_NAME = "intro";
    
    CardSwitcher switcher = null;
    
    //Images
    BufferedImage preyImg;
    BufferedImage predImg;
    BufferedImage classroomImg;
    BufferedImage title1Img;
    BufferedImage title2Img;
    
    //variables
    int rdPosition = 20;
    
    
    /**
     * Creates new form IntroPanel
     */
    public IntroPanel(CardSwitcher p) {
        initComponents();
        
        //Load images
        preyImg = ImageUtil.loadAndResizeImage("chocolate.png", 48, 48);
        predImg = ImageUtil.loadAndResizeImage("Bob.png", 48, 48);
        classroomImg = ImageUtil.loadAndResizeImage("classroom.png", 428, 404);
        title1Img = ImageUtil.loadAndResizeImage("TheLife.png", 288, 72);
        title2Img = ImageUtil.loadAndResizeImage("ofRD.png", 196, 72);
        
        //Timer
        Timer animTimer = new Timer(30, new AnimTimerTick());
        animTimer.start();
        
        //switcher
        switcher = p;
    }
    
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        g.drawImage(classroomImg, 0, 0, this);
        g.drawImage(preyImg, rdPosition, 248, this);
        g.drawImage(predImg, rdPosition - 80, 248, this);
        g.drawImage(title1Img, 70, 72, this);
        g.drawImage(title2Img, 116, 154, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GameButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();

        GameButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        GameButton.setText("Game");
        GameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameButtonActionPerformed(evt);
            }
        });

        infoButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        infoButton.setText("Info");
        infoButton.setToolTipText("");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(GameButton)
                .addGap(58, 58, 58)
                .addComponent(infoButton)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoButton)
                    .addComponent(GameButton))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameButtonActionPerformed
       switcher.switchToCard(GamePanel.CARD_NAME);
    }//GEN-LAST:event_GameButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        switcher.switchToCard(InfoPanel.CARD_NAME);
    }//GEN-LAST:event_infoButtonActionPerformed

    /**
     * Everything inside this actionPerformed will happen every time the
     * animation timer clicks.
     */
    private class AnimTimerTick implements ActionListener {
        public void actionPerformed(ActionEvent ae) {
            //update image positions
            rdPosition += 6;
            if (rdPosition > 725) {
                rdPosition = - 20;
            }
            
            //force redraw
            repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GameButton;
    private javax.swing.JButton infoButton;
    // End of variables declaration//GEN-END:variables
}
